version: "3.9"

services:
  django:
    build: ../
    container_name: django_con
    environment:
      TZ: "Asia/Seoul"
    ports: 
      - "8000:8000"
    volumes:
      - ../:/srv/PleaseGraduate/
    command: bash docker_cmd.sh dev