version: "3.9"

services:
  django:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
    container_name: django_con
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./:/srv/PleaseGraduate/deploy # 실행 후 외부에 PG.sock 생성
    command: bash docker_cmd.sh dev
