# Generated by Django 3.1.4 on 2021-01-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLecture',
            fields=[
                ('subject_num', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=70)),
                ('classification', models.CharField(max_length=45)),
                ('selection', models.CharField(blank=True, max_length=45, null=True)),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'all_lecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('user_year', models.IntegerField(primary_key=True, serialize=False)),
                ('user_dep', models.CharField(max_length=50)),
                ('sum_score', models.IntegerField()),
                ('major_essential', models.IntegerField()),
                ('major_selection', models.IntegerField()),
                ('core_essential', models.IntegerField()),
                ('core_selection', models.IntegerField()),
                ('basic', models.IntegerField()),
                ('ce_list', models.CharField(max_length=100)),
                ('cs_list', models.CharField(max_length=100)),
                ('b_list', models.CharField(max_length=100)),
                ('sum_eng', models.IntegerField()),
                ('pro', models.IntegerField()),
                ('bsm', models.IntegerField()),
                ('build', models.IntegerField()),
                ('pro_acc_list', models.CharField(max_length=100)),
                ('bsm_ess_list', models.CharField(max_length=100)),
                ('bsm_sel_list', models.CharField(max_length=100)),
                ('build_ess_list', models.CharField(max_length=100)),
                ('build_sel_list', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'standard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewLecture',
            fields=[
                ('subject_num', models.OneToOneField(db_column='subject_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.alllecture')),
            ],
            options={
                'db_table': 'new_lecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('subject_num', models.OneToOneField(db_column='subject_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.alllecture')),
                ('group_num', models.IntegerField()),
            ],
            options={
                'db_table': 'subject_group',
                'managed': False,
            },
        ),
    ]
