# Generated by Django 3.1.4 on 2020-12-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
